#include <check.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include "facts.h"
#include "sparql.h"

s_facts *g_f;

const char *movie_dataset[] = {"inception",
                               "is a",
                               "movie",
                               "title",
                               "Inception",
                               "director",
                               "Christopher Nolan",
                               "year",
                               "2010",
                               "genre",
                               "Sci-Fi",
                               "actor",
                               "Leonardo DiCaprio",
                               "actor",
                               "Joseph Gordon-Levitt",
                               "actor",
                               "Elliot Page",
                               NULL,
                               "dark_knight",
                               "is a",
                               "movie",
                               "title",
                               "The Dark Knight",
                               "director",
                               "Christopher Nolan",
                               "year",
                               "2008",
                               "genre",
                               "Action",
                               "actor",
                               "Christian Bale",
                               "actor",
                               "Heath Ledger",
                               "actor",
                               "Gary Oldman",
                               NULL,
                               "interstellar",
                               "is a",
                               "movie",
                               "title",
                               "Interstellar",
                               "director",
                               "Christopher Nolan",
                               "year",
                               "2014",
                               "genre",
                               "Sci-Fi",
                               "actor",
                               "Matthew McConaughey",
                               "actor",
                               "Anne Hathaway",
                               "actor",
                               "Jessica Chastain",
                               NULL,
                               "prestige",
                               "is a",
                               "movie",
                               "title",
                               "The Prestige",
                               "director",
                               "Christopher Nolan",
                               "year",
                               "2006",
                               "genre",
                               "Drama",
                               "actor",
                               "Christian Bale",
                               "actor",
                               "Hugh Jackman",
                               "actor",
                               "Scarlett Johansson",
                               NULL,
                               "memento",
                               "is a",
                               "movie",
                               "title",
                               "Memento",
                               "director",
                               "Christopher Nolan",
                               "year",
                               "2000",
                               "genre",
                               "Thriller",
                               "actor",
                               "Guy Pearce",
                               "actor",
                               "Carrie-Anne Moss",
                               "actor",
                               "Joe Pantoliano",
                               NULL,
                               "pulp_fiction",
                               "is a",
                               "movie",
                               "title",
                               "Pulp Fiction",
                               "director",
                               "Quentin Tarantino",
                               "year",
                               "1994",
                               "genre",
                               "Crime",
                               "actor",
                               "John Travolta",
                               "actor",
                               "Samuel L. Jackson",
                               "actor",
                               "Uma Thurman",
                               NULL,
                               "django",
                               "is a",
                               "movie",
                               "title",
                               "Django Unchained",
                               "director",
                               "Quentin Tarantino",
                               "year",
                               "2012",
                               "genre",
                               "Western",
                               "actor",
                               "Jamie Foxx",
                               "actor",
                               "Christoph Waltz",
                               "actor",
                               "Leonardo DiCaprio",
                               NULL,
                               "inglourious",
                               "is a",
                               "movie",
                               "title",
                               "Inglourious Basterds",
                               "director",
                               "Quentin Tarantino",
                               "year",
                               "2009",
                               "genre",
                               "War",
                               "actor",
                               "Brad Pitt",
                               "actor",
                               "Christoph Waltz",
                               "actor",
                               "Michael Fassbender",
                               NULL,
                               "matrix",
                               "is a",
                               "movie",
                               "title",
                               "The Matrix",
                               "director",
                               "Lana Wachowski",
                               "year",
                               "1999",
                               "genre",
                               "Sci-Fi",
                               "actor",
                               "Keanu Reeves",
                               "actor",
                               "Laurence Fishburne",
                               "actor",
                               "Carrie-Anne Moss",
                               NULL,
                               "john_wick",
                               "is a",
                               "movie",
                               "title",
                               "John Wick",
                               "director",
                               "Chad Stahelski",
                               "year",
                               "2014",
                               "genre",
                               "Action",
                               "actor",
                               "Keanu Reeves",
                               "actor",
                               "Michael Nyqvist",
                               "actor",
                               "Alfie Allen",
                               NULL,
                               "departed",
                               "is a",
                               "movie",
                               "title",
                               "The Departed",
                               "director",
                               "Martin Scorsese",
                               "year",
                               "2006",
                               "genre",
                               "Crime",
                               "actor",
                               "Leonardo DiCaprio",
                               "actor",
                               "Matt Damon",
                               "actor",
                               "Jack Nicholson",
                               NULL,
                               "wolf_wall_street",
                               "is a",
                               "movie",
                               "title",
                               "The Wolf of Wall Street",
                               "director",
                               "Martin Scorsese",
                               "year",
                               "2013",
                               "genre",
                               "Biography",
                               "actor",
                               "Leonardo DiCaprio",
                               "actor",
                               "Jonah Hill",
                               "actor",
                               "Margot Robbie",
                               NULL,
                               "shutter_island",
                               "is a",
                               "movie",
                               "title",
                               "Shutter Island",
                               "director",
                               "Martin Scorsese",
                               "year",
                               "2010",
                               "genre",
                               "Thriller",
                               "actor",
                               "Leonardo DiCaprio",
                               "actor",
                               "Mark Ruffalo",
                               "actor",
                               "Ben Kingsley",
                               NULL,
                               "goodfellas",
                               "is a",
                               "movie",
                               "title",
                               "Goodfellas",
                               "director",
                               "Martin Scorsese",
                               "year",
                               "1990",
                               "genre",
                               "Crime",
                               "actor",
                               "Robert De Niro",
                               "actor",
                               "Ray Liotta",
                               "actor",
                               "Joe Pesci",
                               NULL,
                               "titanic",
                               "is a",
                               "movie",
                               "title",
                               "Titanic",
                               "director",
                               "James Cameron",
                               "year",
                               "1997",
                               "genre",
                               "Romance",
                               "actor",
                               "Leonardo DiCaprio",
                               "actor",
                               "Kate Winslet",
                               "actor",
                               "Billy Zane",
                               NULL,
                               "feeding_sea_lions",
                               "is a",
                               "movie",
                               "title",
                               "Feeding Sea Lions",
                               "director",
                               "Christopher Nolan",
                               "year",
                               "1900",
                               "genre",
                               "Short",
                               "actor",
                               "Paul Boyton",
                               NULL,
                               "the_wonder__ching_ling_foo",
                               "is a",
                               "movie",
                               "title",
                               "The Wonder, Ching Ling Foo",
                               "director",
                               "Christopher Nolan",
                               "year",
                               "1900",
                               "genre",
                               "Short",
                               "actor",
                               "Ching Ling Foo",
                               NULL,
                               "alice_in_wonderland",
                               "is a",
                               "movie",
                               "title",
                               "Alice in Wonderland",
                               "director",
                               "Alfred Hitchcock",
                               "year",
                               "1903",
                               "genre",
                               "Fantasy",
                               "actor",
                               "May Clark",
                               NULL,
                               "the_automobile_thieves",
                               "is a",
                               "movie",
                               "title",
                               "The Automobile Thieves",
                               "director",
                               "Ridley Scott",
                               "year",
                               "1906",
                               "genre",
                               "Short",
                               "actor",
                               "J. Stuart Blackton",
                               "actor",
                               "Florence Lawrence",
                               NULL,
                               "humorous_phases_of_funny_faces",
                               "is a",
                               "movie",
                               "title",
                               "Humorous Phases of Funny Faces",
                               "director",
                               "Ridley Scott",
                               "year",
                               "1906",
                               "genre",
                               "Short",
                               "actor",
                               "J. Stuart Blackton",
                               NULL,
                               "the_female_highwayman",
                               "is a",
                               "movie",
                               "title",
                               "The Female Highwayman",
                               "director",
                               "Stanley Kubrick",
                               "year",
                               "1906",
                               "genre",
                               "Short",
                               "actor",
                               "Margaret Leslie and Howard E. Nicholas",
                               NULL,
                               "ben_hur",
                               "is a",
                               "movie",
                               "title",
                               "Ben Hur",
                               "director",
                               "Alfred Hitchcock",
                               "year",
                               "1907",
                               "genre",
                               "Historical",
                               "actor",
                               "William S. Hart",
                               NULL,
                               "daniel_boone",
                               "is a",
                               "movie",
                               "title",
                               "Daniel Boone",
                               "director",
                               "Steven Spielberg",
                               "year",
                               "1907",
                               "genre",
                               "Biography",
                               "actor",
                               "William Craven",
                               "actor",
                               "Florence Lawrence",
                               NULL,
                               "how_brown_saw_the_baseball_game",
                               "is a",
                               "movie",
                               "title",
                               "How Brown Saw the Baseball Game",
                               "director",
                               "Christopher Nolan",
                               "year",
                               "1907",
                               "genre",
                               "Comedy",
                               "actor",
                               "Unknown",
                               NULL,
                               "laughing_gas",
                               "is a",
                               "movie",
                               "title",
                               "Laughing Gas",
                               "director",
                               "Alfred Hitchcock",
                               "year",
                               "1907",
                               "genre",
                               "Comedy",
                               "actor",
                               "Bertha Regustus",
                               "actor",
                               "Edward Boulden",
                               NULL,
                               "the_adventures_of_dollie",
                               "is a",
                               "movie",
                               "title",
                               "The Adventures of Dollie",
                               "director",
                               "Stanley Kubrick",
                               "year",
                               "1908",
                               "genre",
                               "Drama",
                               "actor",
                               "Arthur V. Johnson",
                               "actor",
                               "Linda Arvidson",
                               NULL,
                               "balked_at_the_altar",
                               "is a",
                               "movie",
                               "title",
                               "Balked at the Altar",
                               "director",
                               "Ridley Scott",
                               "year",
                               "1908",
                               "genre",
                               "Comedy",
                               "actor",
                               "Linda Arvidson",
                               "actor",
                               "George Gebhardt",
                               NULL,
                               "the_bandit_s_waterloo",
                               "is a",
                               "movie",
                               "title",
                               "The Bandit's Waterloo",
                               "director",
                               "Steven Spielberg",
                               "year",
                               "1908",
                               "genre",
                               "Drama",
                               "actor",
                               "Charles Inslee",
                               "actor",
                               "Linda Arvidson",
                               NULL,
                               "the_black_viper",
                               "is a",
                               "movie",
                               "title",
                               "The Black Viper",
                               "director",
                               "Martin Scorsese",
                               "year",
                               "1908",
                               "genre",
                               "Drama",
                               "actor",
                               "D. W. Griffith",
                               NULL,
                               "a_calamitous_elopement",
                               "is a",
                               "movie",
                               "title",
                               "A Calamitous Elopement",
                               "director",
                               "Ridley Scott",
                               "year",
                               "1908",
                               "genre",
                               "Comedy",
                               "actor",
                               "Harry Solter",
                               "actor",
                               "Linda Arvidson",
                               NULL,
                               "the_call_of_the_wild",
                               "is a",
                               "movie",
                               "title",
                               "The Call of the Wild",
                               "director",
                               "Stanley Kubrick",
                               "year",
                               "1908",
                               "genre",
                               "Adventure",
                               "actor",
                               "Charles Inslee",
                               NULL,
                               "a_christmas_carol",
                               "is a",
                               "movie",
                               "title",
                               "A Christmas Carol",
                               "director",
                               "Steven Spielberg",
                               "year",
                               "1908",
                               "genre",
                               "Drama",
                               "actor",
                               "Tom Ricketts",
                               NULL,
                               "deceived_slumming_party",
                               "is a",
                               "movie",
                               "title",
                               "Deceived Slumming Party",
                               "director",
                               "Alfred Hitchcock",
                               "year",
                               "1908",
                               "genre",
                               "Comedy",
                               "actor",
                               "Edward Dillon",
                               "actor",
                               "D. W. Griffith",
                               "actor",
                               "George Gebhardt",
                               NULL,
                               "dr__jekyll_and_mr__hyde",
                               "is a",
                               "movie",
                               "title",
                               "Dr. Jekyll and Mr. Hyde",
                               "director",
                               "Stanley Kubrick",
                               "year",
                               "1908",
                               "genre",
                               "Horror",
                               "actor",
                               "Hobart Bosworth",
                               "actor",
                               "Betty Harte",
                               NULL,
                               "the_fight_for_freedom",
                               "is a",
                               "movie",
                               "title",
                               "The Fight for Freedom",
                               "director",
                               "Christopher Nolan",
                               "year",
                               "1908",
                               "genre",
                               "Western",
                               "actor",
                               "Florence Auer",
                               "actor",
                               "John G. Adolfi",
                               NULL,
                               "macbeth",
                               "is a",
                               "movie",
                               "title",
                               "Macbeth",
                               "director",
                               "Quentin Tarantino",
                               "year",
                               "1908",
                               "genre",
                               "Silent",
                               "actor",
                               "William V. Ranous",
                               "actor",
                               "Paul Panzer",
                               NULL,
                               "money_mad",
                               "is a",
                               "movie",
                               "title",
                               "Money Mad",
                               "director",
                               "Steven Spielberg",
                               "year",
                               "1908",
                               "genre",
                               "Crime",
                               "actor",
                               "Charles Inslee",
                               "actor",
                               "George Gebhardt",
                               NULL,
                               "the_red_man_and_the_child",
                               "is a",
                               "movie",
                               "title",
                               "The Red Man and the Child",
                               "director",
                               "Steven Spielberg",
                               "year",
                               "1908",
                               "genre",
                               "Western",
                               "actor",
                               "Charles Inslee",
                               "actor",
                               "John Tansey",
                               NULL,
                               "romeo_and_juliet",
                               "is a",
                               "movie",
                               "title",
                               "Romeo and Juliet",
                               "director",
                               "Ridley Scott",
                               "year",
                               "1908",
                               "genre",
                               "Silent",
                               "actor",
                               "Paul Panzer",
                               "actor",
                               "Florence Lawrence",
                               NULL,
                               "the_taming_of_the_shrew",
                               "is a",
                               "movie",
                               "title",
                               "The Taming of the Shrew",
                               "director",
                               "Ridley Scott",
                               "year",
                               "1908",
                               "genre",
                               "Silent",
                               "actor",
                               "Florence Lawrence",
                               "actor",
                               "Arthur V. Johnson",
                               NULL,
                               "the_tavern_keeper_s_daughter",
                               "is a",
                               "movie",
                               "title",
                               "The Tavern Keeper's Daughter",
                               "director",
                               "Martin Scorsese",
                               "year",
                               "1908",
                               "genre",
                               "Action",
                               "actor",
                               "George Gebhardt",
                               "actor",
                               "Florence Auer",
                               NULL,
                               "and_a_little_child_shall_lead_them",
                               "is a",
                               "movie",
                               "title",
                               "And a Little Child Shall Lead Them",
                               "director",
                               "Stanley Kubrick",
                               "year",
                               "1909",
                               "genre",
                               "Drama",
                               "actor",
                               "Marion Leonard",
                               "actor",
                               "Arthur V. Johnson",
                               NULL,
                               "at_the_altar",
                               "is a",
                               "movie",
                               "title",
                               "At the Altar",
                               "director",
                               "Stanley Kubrick",
                               "year",
                               "1909",
                               "genre",
                               "Drama",
                               "actor",
                               "Marion Leonard",
                               NULL,
                               "the_brahma_diamond",
                               "is a",
                               "movie",
                               "title",
                               "The Brahma Diamond",
                               "director",
                               "Stanley Kubrick",
                               "year",
                               "1909",
                               "genre",
                               "Drama",
                               "actor",
                               "Harry Solter",
                               "actor",
                               "Florence Lawrence",
                               NULL,
                               "a_burglar_s_mistake",
                               "is a",
                               "movie",
                               "title",
                               "A Burglar's Mistake",
                               "director",
                               "Christopher Nolan",
                               "year",
                               "1909",
                               "genre",
                               "Drama",
                               "actor",
                               "Harry Solter",
                               "actor",
                               "Charles Inslee",
                               NULL,
                               "the_cord_of_life_1_",
                               "is a",
                               "movie",
                               "title",
                               "The Cord of Life[1]",
                               "director",
                               "Martin Scorsese",
                               "year",
                               "1909",
                               "genre",
                               "Drama",
                               "actor",
                               "Charles Inslee",
                               "actor",
                               "Marion Leonard",
                               NULL,
                               "the_criminal_hypnotist",
                               "is a",
                               "movie",
                               "title",
                               "The Criminal Hypnotist",
                               "director",
                               "Martin Scorsese",
                               "year",
                               "1909",
                               "genre",
                               "Drama",
                               "actor",
                               "Owen Moore",
                               "actor",
                               "Marion Leonard",
                               NULL,
                               "the_curtain_pole_1_",
                               "is a",
                               "movie",
                               "title",
                               "The Curtain Pole[1]",
                               "director",
                               "Martin Scorsese",
                               "year",
                               "1909",
                               "genre",
                               "Comedy",
                               "actor",
                               "Mack Sennett",
                               NULL,
                               "a_drunkard_s_reformation",
                               "is a",
                               "movie",
                               "title",
                               "A Drunkard's Reformation",
                               "director",
                               "Steven Spielberg",
                               "year",
                               "1909",
                               "genre",
                               "Drama",
                               "actor",
                               "Arthur V. Johnson",
                               NULL,
                               "edgar_allan_poe",
                               "is a",
                               "movie",
                               "title",
                               "Edgar Allan Poe",
                               "director",
                               "Martin Scorsese",
                               "year",
                               "1909",
                               "genre",
                               "Drama",
                               "actor",
                               "Barry O'Moore",
                               "actor",
                               "Linda Arvidson",
                               NULL,
                               "a_fool_s_revenge",
                               "is a",
                               "movie",
                               "title",
                               "A Fool's Revenge",
                               "director",
                               "Quentin Tarantino",
                               "year",
                               "1909",
                               "genre",
                               "Drama",
                               "actor",
                               "Owen Moore",
                               NULL,
                               "the_girls_and_daddy_1_",
                               "is a",
                               "movie",
                               "title",
                               "The Girls and Daddy[1]",
                               "director",
                               "Quentin Tarantino",
                               "year",
                               "1909",
                               "genre",
                               "Drama",
                               "actor",
                               "Florence Lawrence",
                               NULL,
                               "the_hindoo_dagger",
                               "is a",
                               "movie",
                               "title",
                               "The Hindoo Dagger",
                               "director",
                               "Ridley Scott",
                               "year",
                               "1909",
                               "genre",
                               "Drama",
                               "actor",
                               "Harry Solter",
                               NULL,
                               "his_ward_s_love",
                               "is a",
                               "movie",
                               "title",
                               "His Ward's Love",
                               "director",
                               "Christopher Nolan",
                               "year",
                               "1909",
                               "genre",
                               "Short",
                               "actor",
                               "Arthur V. Johnson",
                               NULL,
                               "his_wife_s_mother",
                               "is a",
                               "movie",
                               "title",
                               "His Wife's Mother",
                               "director",
                               "Stanley Kubrick",
                               "year",
                               "1909",
                               "genre",
                               "Comedy",
                               "actor",
                               "John R. Cumpson",
                               NULL,
                               "the_honor_of_thieves",
                               "is a",
                               "movie",
                               "title",
                               "The Honor of Thieves",
                               "director",
                               "Alfred Hitchcock",
                               "year",
                               "1909",
                               "genre",
                               "Drama",
                               "actor",
                               "Harry Solter",
                               NULL,
                               "the_joneses_have_amateur_theatricals",
                               "is a",
                               "movie",
                               "title",
                               "The Joneses Have Amateur Theatricals",
                               "director",
                               "Alfred Hitchcock",
                               "year",
                               "1909",
                               "genre",
                               "Comedy",
                               "actor",
                               "John R. Cumpson",
                               NULL,
                               "the_life_of_moses",
                               "is a",
                               "movie",
                               "title",
                               "The Life of Moses",
                               "director",
                               "Alfred Hitchcock",
                               "year",
                               "1909",
                               "genre",
                               "Silent",
                               "actor",
                               "Pat Hartigan",
                               "actor",
                               "Julia Arthur",
                               "actor",
                               "William J. Humphrey",
                               NULL,
                               "love_finds_a_way",
                               "is a",
                               "movie",
                               "title",
                               "Love Finds a Way",
                               "director",
                               "Martin Scorsese",
                               "year",
                               "1909",
                               "genre",
                               "Drama",
                               "actor",
                               "Anita Hendrie",
                               NULL,
                               "the_lure_of_the_gown",
                               "is a",
                               "movie",
                               "title",
                               "The Lure of the Gown",
                               "director",
                               "Quentin Tarantino",
                               "year",
                               "1909",
                               "genre",
                               "Drama",
                               "actor",
                               "Marion Leonard",
                               NULL,
                               "those_awful_hats",
                               "is a",
                               "movie",
                               "title",
                               "Those Awful Hats",
                               "director",
                               "Quentin Tarantino",
                               "year",
                               "1909",
                               "genre",
                               "Comedy",
                               "actor",
                               "Mack Sennett",
                               NULL,
                               "an_arcadian_maid",
                               "is a",
                               "movie",
                               "title",
                               "An Arcadian Maid",
                               "director",
                               "Christopher Nolan",
                               "year",
                               "1910",
                               "genre",
                               "Drama",
                               "actor",
                               "Mary Pickford",
                               "actor",
                               "Mack Sennett",
                               NULL,
                               "as_it_is_in_life",
                               "is a",
                               "movie",
                               "title",
                               "As It Is in Life",
                               "director",
                               "Alfred Hitchcock",
                               "year",
                               "1910",
                               "genre",
                               "Romance",
                               "actor",
                               "George Nichols",
                               "actor",
                               "Gladys Egan",
                               "actor",
                               "Mary Pickford",
                               NULL,
                               "the_courtship_of_miles_standish",
                               "is a",
                               "movie",
                               "title",
                               "The Courtship of Miles Standish",
                               "director",
                               "Ridley Scott",
                               "year",
                               "1910",
                               "genre",
                               "Drama",
                               "actor",
                               "Robert Z. Leonard",
                               NULL,
                               "the_englishman_and_the_girl",
                               "is a",
                               "movie",
                               "title",
                               "The Englishman and the Girl",
                               "director",
                               "Stanley Kubrick",
                               "year",
                               "1910",
                               "genre",
                               "Comedy",
                               "actor",
                               "Charles Craig",
                               "actor",
                               "Mary Pickford",
                               NULL,
                               "frankenstein",
                               "is a",
                               "movie",
                               "title",
                               "Frankenstein",
                               "director",
                               "Alfred Hitchcock",
                               "year",
                               "1910",
                               "genre",
                               "Horror",
                               "actor",
                               "Augustus Phillips",
                               "actor",
                               "Charles Stanton Ogle",
                               "actor",
                               "Mary Fuller",
                               NULL,
                               "the_fugitive",
                               "is a",
                               "movie",
                               "title",
                               "The Fugitive",
                               "director",
                               "Ridley Scott",
                               "year",
                               "1910",
                               "genre",
                               "Drama",
                               "actor",
                               "Kate Bruce",
                               "actor",
                               "Edward Dillon",
                               NULL,
                               "the_house_with_closed_shutters",
                               "is a",
                               "movie",
                               "title",
                               "The House with Closed Shutters",
                               "director",
                               "Alfred Hitchcock",
                               "year",
                               "1910",
                               "genre",
                               "Drama",
                               "actor",
                               "Henry B. Walthall",
                               NULL,
                               "in_old_california",
                               "is a",
                               "movie",
                               "title",
                               "In Old California",
                               "director",
                               "Alfred Hitchcock",
                               "year",
                               "1910",
                               "genre",
                               "Drama",
                               "actor",
                               "Frank Powell",
                               "actor",
                               "Arthur V. Johnson",
                               "actor",
                               "Marion Leonard",
                               NULL,
                               "in_the_border_states",
                               "is a",
                               "movie",
                               "title",
                               "In the Border States",
                               "director",
                               "Steven Spielberg",
                               "year",
                               "1910",
                               "genre",
                               "Drama",
                               "actor",
                               "Charles West",
                               NULL,
                               "the_lad_from_old_ireland",
                               "is a",
                               "movie",
                               "title",
                               "The Lad from Old Ireland",
                               "director",
                               "Stanley Kubrick",
                               "year",
                               "1910",
                               "genre",
                               "Drama",
                               "actor",
                               "Sidney Olcott",
                               "actor",
                               "Gene Gauntier",
                               "actor",
                               "Thomas O'Connor",
                               NULL,
                               "pocahontas",
                               "is a",
                               "movie",
                               "title",
                               "Pocahontas",
                               "director",
                               "Martin Scorsese",
                               "year",
                               "1910",
                               "genre",
                               "Short",
                               "actor",
                               "Anna Rosemond",
                               "actor",
                               "George Barnes",
                               "actor",
                               "Frank H. Crane",
                               NULL,
                               "pride_of_the_range",
                               "is a",
                               "movie",
                               "title",
                               "Pride of the Range",
                               "director",
                               "Quentin Tarantino",
                               "year",
                               "1910",
                               "genre",
                               "Western",
                               "actor",
                               "Tom Mix",
                               NULL,
                               "ramona",
                               "is a",
                               "movie",
                               "title",
                               "Ramona",
                               "director",
                               "Martin Scorsese",
                               "year",
                               "1910",
                               "genre",
                               "Drama",
                               "actor",
                               "Mary Pickford",
                               "actor",
                               "Henry B. Walthall",
                               NULL,
                               "the_rocky_road",
                               "is a",
                               "movie",
                               "title",
                               "The Rocky Road",
                               "director",
                               "Alfred Hitchcock",
                               "year",
                               "1910",
                               "genre",
                               "Drama",
                               "actor",
                               "Frank Powell",
                               "actor",
                               "Stephanie Longfellow",
                               NULL,
                               "roosevelt_in_africa",
                               "is a",
                               "movie",
                               "title",
                               "Roosevelt in Africa",
                               "director",
                               "Martin Scorsese",
                               "year",
                               "1910",
                               "genre",
                               "Documentary",
                               "actor",
                               "Theodore Roosevelt",
                               NULL,
                               "rose_o_salem_town",
                               "is a",
                               "movie",
                               "title",
                               "Rose O'Salem-Town",
                               "director",
                               "Steven Spielberg",
                               "year",
                               "1910",
                               "genre",
                               "Drama",
                               "actor",
                               "Henry B. Walthall",
                               NULL,
                               "the_sanitarium",
                               "is a",
                               "movie",
                               "title",
                               "The Sanitarium",
                               "director",
                               "Stanley Kubrick",
                               "year",
                               "1910",
                               "genre",
                               "Comedy",
                               "actor",
                               "Roscoe \"Fatty\" Arbuckle",
                               NULL,
                               "the_two_brothers",
                               "is a",
                               "movie",
                               "title",
                               "The Two Brothers",
                               "director",
                               "Alfred Hitchcock",
                               "year",
                               "1910",
                               "genre",
                               "Western",
                               "actor",
                               "Arthur V. Johnson",
                               NULL,
                               "the_unchanging_sea",
                               "is a",
                               "movie",
                               "title",
                               "The Unchanging Sea",
                               "director",
                               "Ridley Scott",
                               "year",
                               "1910",
                               "genre",
                               "Drama",
                               "actor",
                               "Arthur V. Johnson",
                               NULL,
                               "the_woman_from_mellon_s",
                               "is a",
                               "movie",
                               "title",
                               "The Woman from Mellon's",
                               "director",
                               "Martin Scorsese",
                               "year",
                               "1910",
                               "genre",
                               "Short",
                               "actor",
                               "Billy Quirk",
                               "actor",
                               "Mary Pickford",
                               NULL,
                               "the_wonderful_wizard_of_oz",
                               "is a",
                               "movie",
                               "title",
                               "The Wonderful Wizard of Oz",
                               "director",
                               "Christopher Nolan",
                               "year",
                               "1910",
                               "genre",
                               "Fantasy",
                               "actor",
                               "Bebe Daniels",
                               NULL,
                               "baseball_and_bloomers",
                               "is a",
                               "movie",
                               "title",
                               "Baseball and Bloomers",
                               "director",
                               "Ridley Scott",
                               "year",
                               "1911",
                               "genre",
                               "Silent",
                               "actor",
                               "William Garwood",
                               "actor",
                               "Marguerite Snow",
                               NULL,
                               "the_black_arrow__a_tale_of_the_two_roses",
                               "is a",
                               "movie",
                               "title",
                               "The Black Arrow: A Tale of the Two Roses",
                               "director",
                               "Steven Spielberg",
                               "year",
                               "1911",
                               "genre",
                               "Drama",
                               "actor",
                               "Charles Ogle",
                               "actor",
                               "Natalie Jerome",
                               NULL,
                               "brown_of_harvard",
                               "is a",
                               "movie",
                               "title",
                               "Brown of Harvard",
                               "director",
                               "Martin Scorsese",
                               "year",
                               "1911",
                               "genre",
                               "Drama",
                               "actor",
                               "Edgar G. Wynn",
                               "actor",
                               "Edgar Kennedy",
                               NULL,
                               "cally_s_comet",
                               "is a",
                               "movie",
                               "title",
                               "Cally's Comet",
                               "director",
                               "Ridley Scott",
                               "year",
                               "1911",
                               "genre",
                               "Drama",
                               "actor",
                               "William Garwood",
                               NULL,
                               "the_coffin_ship",
                               "is a",
                               "movie",
                               "title",
                               "The Coffin Ship",
                               "director",
                               "Alfred Hitchcock",
                               "year",
                               "1911",
                               "genre",
                               "Adventure",
                               "actor",
                               "William Garwood",
                               NULL,
                               "the_colonel_and_the_king",
                               "is a",
                               "movie",
                               "title",
                               "The Colonel and the King",
                               "director",
                               "Christopher Nolan",
                               "year",
                               "1911",
                               "genre",
                               "Drama",
                               "actor",
                               "Marie Eline",
                               "actor",
                               "William Garwood",
                               NULL,
                               "courting_across_the_court",
                               "is a",
                               "movie",
                               "title",
                               "Courting Across the Court",
                               "director",
                               "Alfred Hitchcock",
                               "year",
                               "1911",
                               "genre",
                               "Romance",
                               "actor",
                               "William Garwood",
                               NULL,
                               "the_cowboy_and_the_lady",
                               "is a",
                               "movie",
                               "title",
                               "The Cowboy and the Lady",
                               "director",
                               "Ridley Scott",
                               "year",
                               "1911",
                               "genre",
                               "Western",
                               "actor",
                               "Alan Hale",
                               NULL,
                               NULL};

void setup(void)
{
    g_f = new_facts(NULL, 1000);
    ck_assert(g_f);
    ck_assert_int_eq(0, facts_add(g_f, movie_dataset));
}

void teardown(void)
{
    delete_facts(g_f);
    g_f = NULL;
}

int has_value(const char **arr, int size, const char *val)
{
    for (int i = 0; i < size; i++) {
        if (strcmp(arr[i], val) == 0) {
            return 1;
        }
    }
    return 0;
}

START_TEST(test_nolan_scifi)
{
    // Find Sci-Fi movies directed by Christopher Nolan
    const char *movie;
    s_binding bindings[] = {{"?movie", &movie}, {NULL, NULL}};
    s_facts_with_cursor cur;

    int rc = facts_sparql(g_f, bindings, &cur,
                          "SELECT ?movie WHERE { ?movie <director> \"Christopher Nolan\" . ?movie <genre> \"Sci-Fi\" . }");
    ck_assert_int_eq(0, rc);

    const char *results[10];
    int count = 0;
    while (facts_with_cursor_next(&cur)) {
        ck_assert(count < 10);
        results[count++] = facts_get_prop(g_f, movie, "title");
    }
    facts_with_cursor_destroy(&cur);

    ck_assert_int_eq(2, count);
    ck_assert(has_value(results, count, "Inception"));
    ck_assert(has_value(results, count, "Interstellar"));
}
END_TEST

START_TEST(test_dicaprio_movies)
{
    // Find all movies starring Leonardo DiCaprio
    const char *movie;
    s_binding bindings[] = {{"?movie", &movie}, {NULL, NULL}};
    s_facts_with_cursor cur;

    int rc = facts_sparql(g_f, bindings, &cur, "SELECT ?movie WHERE { ?movie <actor> \"Leonardo DiCaprio\" . }");
    ck_assert_int_eq(0, rc);

    const char *results[10];
    int count = 0;
    while (facts_with_cursor_next(&cur)) {
        ck_assert(count < 10);
        results[count++] = facts_get_prop(g_f, movie, "title");
    }
    facts_with_cursor_destroy(&cur);

    ck_assert_int_eq(6, count);
    ck_assert(has_value(results, count, "Inception"));
    ck_assert(has_value(results, count, "Django Unchained"));
    ck_assert(has_value(results, count, "The Departed"));
    ck_assert(has_value(results, count, "The Wolf of Wall Street"));
    ck_assert(has_value(results, count, "Shutter Island"));
    ck_assert(has_value(results, count, "Titanic"));
}
END_TEST

START_TEST(test_dicaprio_directors)
{
    // Find directors who directed Leonardo DiCaprio
    const char *movie;
    const char *director;
    s_binding bindings[] = {{"?movie", &movie}, {"?director", &director}, {NULL, NULL}};
    s_facts_with_cursor cur;

    int rc = facts_sparql(g_f, bindings, &cur,
                          "SELECT ?movie ?director WHERE { ?movie <actor> \"Leonardo DiCaprio\" . ?movie <director> ?director . }");
    ck_assert_int_eq(0, rc);

    const char *results[10];
    int count = 0;
    while (facts_with_cursor_next(&cur)) {
        ck_assert(count < 10);
        const char *dir_name = director;
        if (!has_value(results, count, dir_name)) {
            results[count++] = dir_name;
        }
    }
    facts_with_cursor_destroy(&cur);

    ck_assert_int_eq(4, count);
    ck_assert(has_value(results, count, "Christopher Nolan"));
    ck_assert(has_value(results, count, "Quentin Tarantino"));
    ck_assert(has_value(results, count, "Martin Scorsese"));
    ck_assert(has_value(results, count, "James Cameron"));
}
END_TEST

START_TEST(test_matrix_actors)
{
    // Find all actors who starred in Memento and The Matrix
    // Carrie-Anne Moss is in both
    const char *actor;
    s_binding bindings[] = {{"?actor", &actor}, {NULL, NULL}};
    s_facts_with_cursor cur;

    int rc = facts_sparql(g_f, bindings, &cur, "SELECT ?actor WHERE { <memento> <actor> ?actor . <matrix> <actor> ?actor . }");
    ck_assert_int_eq(0, rc);

    const char *results[5];
    int count = 0;
    while (facts_with_cursor_next(&cur)) {
        ck_assert(count < 5);
        results[count++] = actor;
    }
    facts_with_cursor_destroy(&cur);

    ck_assert_int_eq(1, count);
    ck_assert_str_eq("Carrie-Anne Moss", results[0]);
}
END_TEST

START_TEST(test_year_filter)
{
    // Find movies released in 2010 or later
    const char *movie;
    s_binding bindings[] = {{"?movie", &movie}, {NULL, NULL}};
    s_facts_with_cursor cur;

    int rc = facts_sparql(g_f, bindings, &cur, "SELECT ?movie WHERE { ?movie <is a> <movie> . }");
    ck_assert_int_eq(0, rc);

    const char *results[15];
    int count = 0;
    while (facts_with_cursor_next(&cur)) {
        long year = facts_get_prop_long(g_f, movie, "year");
        if (year >= 2010) {
            ck_assert(count < 15);
            results[count++] = facts_get_prop(g_f, movie, "title");
        }
    }
    facts_with_cursor_destroy(&cur);

    ck_assert_int_eq(6, count);
    ck_assert(has_value(results, count, "Inception"));               // 2010
    ck_assert(has_value(results, count, "Interstellar"));            // 2014
    ck_assert(has_value(results, count, "Django Unchained"));        // 2012
    ck_assert(has_value(results, count, "John Wick"));               // 2014
    ck_assert(has_value(results, count, "The Wolf of Wall Street")); // 2013
    ck_assert(has_value(results, count, "Shutter Island"));          // 2010
}
END_TEST

Suite *movie_integration_suite(void)
{
    Suite *s = suite_create("Movie Integration");
    TCase *tc = tcase_create("Queries");
    tcase_add_checked_fixture(tc, setup, teardown);
    tcase_add_test(tc, test_nolan_scifi);
    tcase_add_test(tc, test_dicaprio_movies);
    tcase_add_test(tc, test_dicaprio_directors);
    tcase_add_test(tc, test_matrix_actors);
    tcase_add_test(tc, test_year_filter);
    suite_add_tcase(s, tc);
    return s;
}

int main(void)
{
    int number_failed;
    Suite *s = movie_integration_suite();
    SRunner *sr = srunner_create(s);

    srunner_run_all(sr, CK_NORMAL);
    number_failed = srunner_ntests_failed(sr);
    srunner_free(sr);
    return (number_failed == 0) ? 0 : 1;
}
